empty: [
    "AccessionNumber",
    "ReferringPhysicianName",
    "ConsultingPhysicianName",
    "PatientBirthDate",
    "ClinicalTrialProtocolName",
    "ClinicalTrialSiteID",
    "ClinicalTrialSiteName",
    "ClinicalTrialTimePointID",
    "ClinicalTrialCoordinatingCenterName",
    "StudyID",
    "PlacerOrderNumberImagingServiceRequest",
    "FillerOrderNumberImagingServiceRequest",
    "ContentCreatorName",
    "SourceOfPreviousValues",
    "BarcodeValue",
    "ROIInterpreter",
    "SourceSerialNumber",
    "TreatmentMachineName",
    "RTAccessoryHolderSlotID",
    "RTAccessoryDeviceSlotID",
    "DeviceAlternateIdentifier",
    "ManufacturerDeviceIdentifier"
]

remove: [
    "AffectedSOPInstanceUID",
    "InstitutionName",
    "InstitutionAddress",
    "InstitutionCodeSequence",
    "ReferringPhysicianAddress",
    "ReferringPhysicianTelephoneNumbers",
    "ReferringPhysicianIdentificationSequence",
    "ConsultingPhysicianIdentificationSequence",
    "TimezoneOffsetFromUTC",
    "StationName",
    "InstitutionalDepartmentName",
    "InstitutionalDepartmentTypeCodeSequence",
    "PhysiciansOfRecord",
    "PhysiciansOfRecordIdentificationSequence",
    "PerformingPhysicianName",
    "PerformingPhysicianIdentificationSequence",
    "NameOfPhysiciansReadingStudy",
    "PhysiciansReadingStudyIdentificationSequence",
    "OperatorsName",
    "OperatorIdentificationSequence",
    "ReferencedPatientSequence",
    "DerivationDescription",
    "IdentifyingComments",
    "IssuerOfPatientID",
    "PatientBirthTime",
    "PatientInsurancePlanCodeSequence",
    "PatientPrimaryLanguageCodeSequence",
    "PatientPrimaryLanguageModifierCodeSequence",
    "OtherPatientIDs",
    "OtherPatientNames",
    "OtherPatientIDsSequence",
    "PatientBirthName",
    "PatientAddress",
    "InsurancePlanIdentification",
    "PatientMotherBirthName",
    "MilitaryRank",
    "BranchOfService",
    "MedicalRecordLocator",
    "ReferencedPatientPhotoSequence",
    "Allergies",
    "CountryOfResidence",
    "RegionOfResidence",
    "PatientTelephoneNumbers",
    "PatientTelecomInformation",
    "Occupation",
    "PatientReligiousPreference",
    "ResponsiblePerson",
    "ResponsibleOrganization",
    "PatientComments",
    "ClinicalTrialSeriesID",
    "ClinicalTrialProtocolEthicsCommitteeApprovalNumber",
    "CameraOwnerName",
    "LensSpecification",
    "LensMake",
    "LensModel",
    "LensSerialNumber",
    "GPSVersionID",
    "GPSLatitudeRef",
    "GPSLatitude",
    "GPSLongitudeRef",
    "GPSLongitude",
    "GPSAltitudeRef",
    "GPSAltitude",
    "GPSTimeStamp",
    "GPSSatellites",
    "GPSStatus",
    "GPSMeasureMode",
    "GPSDOP",
    "GPSSpeedRef",
    "GPSSpeed",
    "GPSTrackRef",
    "GPSTrack",
    "GPSImgDirectionRef",
    "GPSImgDirection",
    "GPSMapDatum",
    "GPSDestLatitudeRef",
    "GPSDestLatitude",
    "GPSDestLongitudeRef",
    "GPSDestLongitude",
    "GPSDestBearingRef",
    "GPSDestBearing",
    "GPSDestDistanceRef",
    "GPSDestDistance",
    "GPSProcessingMethod",
    "GPSAreaInformation",
    "GPSDifferential",
    "DeviceSerialNumber",
    "PlateID",
    "GeneratorID",
    "CassetteID",
    "GantryID",
    "UniqueDeviceIdentifier",
    "UDISequence",
    "DateOfLastCalibration",
    "TimeOfLastCalibration",
    "TransducerIdentificationSequence",
    "DetectorID",
    "XRayDetectorLabel",
    "ModifyingDeviceID",
    "ModifiedImageDescription",
    "ImageComments",
    "FrameComments",
    "ImagePresentationComments",
    "StudyIDIssuer",
    "ScheduledStudyLocation",
    "ScheduledStudyLocationAETitle",
    "RequestingPhysician",
    "RequestingService",
    "ReasonForVisit",
    "ReasonForVisitCodeSequence",
    "StudyComments",
    "FrameOriginTimestamp",
    "ReferencedPatientAliasSequence",
    "AdmissionID",
    "IssuerOfAdmissionID",
    "IssuerOfAdmissionIDSequence",
    "ScheduledPatientInstitutionResidence",
    "SpecialNeeds",
    "ServiceEpisodeID",
    "IssuerOfServiceEpisodeID",
    "IssuerOfServiceEpisodeIDSequence",
    "CurrentPatientLocation",
    "PatientInstitutionResidence",
    "PatientState",
    "VisitComments",
    "ScheduledStationAETitle",
    "ScheduledPerformingPhysicianName",
    "ScheduledProcedureStepID",
    "ScheduledPerformingPhysicianIdentificationSequence",
    "ScheduledStationName",
    "ScheduledProcedureStepLocation",
    "PerformedStationAETitle",
    "PerformedStationName",
    "PerformedLocation",
    "PerformedProcedureStepID",
    "RequestAttributesSequence",
    "CommentsOnThePerformedProcedureStep",
    "CommentsOnRadiationDose",
    "SpecimenAccessionNumber",
    "SlideIdentifier",
    "RequestedProcedureID",
    "ReasonForTheRequestedProcedure",
    "PatientTransportArrangements",
    "RequestedProcedureLocation",
    "ReasonForRequestedProcedureCodeSequence",
    "NamesOfIntendedRecipientsOfResults",
    "IntendedRecipientsOfResultsIdentificationSequence",
    "PersonAddress",
    "PersonTelephoneNumbers",
    "PersonTelecomInformation",
    "RequestedProcedureComments",
    "ReasonForTheImagingServiceRequest",
    "OrderEnteredBy",
    "OrderEntererLocation",
    "OrderCallbackPhoneNumber",
    "OrderCallbackTelecomInformation",
    "ConfidentialityConstraintOnPatientDataDescription",
    "ScheduledStationNameCodeSequence",
    "ScheduledStationGeographicLocationCodeSequence",
    "PerformedStationNameCodeSequence",
    "PerformedStationGeographicLocationCodeSequence",
    "ScheduledHumanPerformersSequence",
    "ActualHumanPerformersSequence",
    "HumanPerformerOrganization",
    "HumanPerformerName",
    "AuthorObserverSequence",
    "ParticipantSequence",
    "CustodialOrganizationSequence",
    "VerifyingObserverIdentificationCodeSequence",
    "CurrentObserverTrial",
    "VerbalSourceTrial",
    "AddressTrial",
    "TelephoneNumberTrial",
    "VerbalSourceIdentifierCodeSequenceTrial",
    "ContainerComponentID",
    "DeviceDescription",
    "GraphicAnnotationSequence",
    "ContentCreatorIdentificationCodeSequence",
    "SelectorOBValue",
    "SelectorPNValue",
    "SelectorUNValue",
    "SelectorURValue",
    "IconImageSequence",
    "TopicTitle",
    "TopicSubject",
    "TopicAuthor",
    "TopicKeywords",
    "CertificateOfSigner",
    "CertifiedTimestamp",
    "ReferencedDigitalSignatureSequence",
    "ReferencedSOPInstanceMACSequence",
    "MAC",
    "ModifiedAttributesSequence",
    "NonconformingModifiedAttributesSequence",
    "NonconformingDataElementValue",
    "OriginalAttributesSequence",
    "InstanceOriginStatus",
    "TextString",
    "SourceManufacturer",
    "TreatmentTechniqueNotes",
    "PrescriptionNotes",
    "FractionationNotes",
    "PrescriptionNotesSequence",
    "Arbitrary",
    "TextComments",
    "ResultsID",
    "ResultsIDIssuer",
    "InterpretationRecordedDate",
    "InterpretationRecordedTime",
    "InterpretationRecorder",
    "InterpretationTranscriptionDate",
    "InterpretationTranscriptionTime",
    "InterpretationTranscriber",
    "InterpretationAuthor",
    "InterpretationApproverSequence",
    "InterpretationApprovalDate",
    "InterpretationApprovalTime",
    "PhysicianApprovingInterpretation",
    "ResultsDistributionListSequence",
    "DistributionName",
    "DistributionAddress",
    "InterpretationID",
    "InterpretationIDIssuer",
    "DigitalSignaturesSequence",
    "DataSetTrailingPadding",
    "NetworkID",
    "Originator",
    "PositionAcquisitionTemplateDescription",
    "PositionAcquisitionTemplateName",
    "ReceivingAE",
    "RequestingAE",
    "RetrieveAETitle",
    "SelectorAEValue",
    "StationAETitle",
    "ClinicalTrialSponsorName",
    "ClinicalTrialProtocolID",
    "ClinicalTrialSubjectID",
    "ClinicalTrialSubjectReadingID",
    "ClinicalTrialProtocolEthicsCommitteeName",
    "XRaySourceID",
    "XRayDetectorID",
    "FlowIdentifier",
    "SourceIdentifier",
    "ContainerIdentifier",
    "SpecimenIdentifier",
    "PersonIdentificationCodeSequence",
    "VerifyingOrganization",
    "VerifyingObserverName",
    "PersonName",
    "EncapsulatedDocument",
    "ModifyingSystem",
    "DeviceLabel",
    "TreatmentSite",
    "DestinationAE"
]


hash: [
    "RequestedSOPInstanceUID",
    "MediaStorageSOPInstanceUID",
    "ReferencedSOPInstanceUIDInFile",
    "InstanceCreatorUID",
    "AcquisitionUID",
    "SOPInstanceUID",
    "PyramidUID",
    "FailedSOPInstanceUIDList",
    "ReferencedSOPInstanceUID",
    "TransactionUID",
    "IrradiationEventUID",
    "DeviceUID",
    "ManufacturerDeviceClassUID",
    "TargetUID",
    "StudyInstanceUID",
    "SeriesInstanceUID",
    "FrameOfReferenceUID",
    "SynchronizationFrameOfReferenceUID",
    "ConcatenationUID",
    "DimensionOrganizationUID",
    "PaletteColorLookupTableUID",
    "LargePaletteColorLookupTableUID",
    "MultiplexGroupUID",
    "SpecimenUID",
    "ReferencedGeneralPurposeScheduledProcedureStepTransactionUID",
    "UID",
    "ObservationUID",
    "ReferencedObservationUIDTrial",
    "ObservationSubjectUIDTrial",
    "TemplateExtensionOrganizationUID",
    "TemplateExtensionCreatorUID",
    "TrackingUID",
    "AnnotationGroupUID",
    "FiducialUID",
    "PresentationDisplayCollectionUID",
    "PresentationSequenceCollectionUID",
    "StorageMediaFileSetUID",
    "DigitalSignatureUID",
    "ReferencedFrameOfReferenceUID",
    "RelatedFrameOfReferenceUID",
    "DoseReferenceUID",
    "ReferencedDoseReferenceUID",
    "TreatmentPositionGroupUID",
    "PatientSetupUID",
    "TreatmentSessionUID",
    "ReferencedTreatmentPositionGroupUID",
    "ConceptualVolumeUID",
    "ReferencedConceptualVolumeUID",
    "ConstituentConceptualVolumeUID",
    "SourceConceptualVolumeUID",
    "ReferencedFiducialsUID",
    "RTTreatmentPhaseUID",
    "DosimetricObjectiveUID",
    "ReferencedDosimetricObjectiveUID",
    "SourceFrameOfReferenceUID"
]

increment_date: [
    "InstanceCreationDate",
    "InstanceCoercionDateTime",
    "StudyDate",
    "SeriesDate",
    "AcquisitionDate",
    "ContentDate",
    "OverlayDate",
    "CurveDate",
    "AcquisitionDateTime",
    "LastMenstrualDate",
    "EthicsCommitteeApprovalEffectivenessStartDate",
    "EthicsCommitteeApprovalEffectivenessEndDate",
    "CalibrationDate",
    "GPSDateStamp",
    "DateOfSecondaryCapture",
    "RadiopharmaceuticalStartDateTime",
    "RadiopharmaceuticalStopDateTime",
    "DateTimeOfLastCalibration",
    "CalibrationDateTime",
    "DateOfLastDetectorCalibration",
    "FrameAcquisitionDateTime",
    "FrameReferenceDateTime",
    "SourceStartDateTime",
    "SourceEndDateTime",
    "StartAcquisitionDateTime",
    "EndAcquisitionDateTime",
    "DecayCorrectionDateTime",
    "ExclusionStartDateTime",
    "InstructionPerformedDateTime",
    "ContributionDateTime",
    "ModifiedImageDate",
    "StudyVerifiedDate",
    "StudyReadDate",
    "ScheduledStudyStartDate",
    "ScheduledStudyStopDate",
    "StudyArrivalDate",
    "StudyCompletionDate",
    "ScheduledAdmissionDate",
    "ScheduledDischargeDate",
    "AdmittingDate",
    "DischargeDate",
    "ImpedanceMeasurementDateTime",
    "ScheduledProcedureStepStartDate",
    "ScheduledProcedureStepEndDate",
    "PerformedProcedureStepStartDate",
    "PerformedProcedureStepEndDate",
    "IssueDateOfImagingServiceRequest",
    "ScheduledProcedureStepStartDateTime",
    "ScheduledProcedureStepExpirationDateTime",
    "ScheduledProcedureStepModificationDateTime",
    "ExpectedCompletionDateTime",
    "PerformedProcedureStepStartDateTime",
    "PerformedProcedureStepEndDateTime",
    "ProcedureStepCancellationDateTime",
    "FindingsGroupRecordingDateTrial",
    "FindingsGroupRecordingTimeTrial",
    "VerificationDateTime",
    "ObservationDateTime",
    "ObservationStartDateTime",
    "ParticipationDateTime",
    "DateTime",
    "Date",
    "ReferencedDateTime",
    "ObservationDateTrial",
    "ApprovalStatusDateTime",
    "ProductExpirationDateTime",
    "SubstanceAdministrationDateTime",
    "AssertionDateTime",
    "AssertionExpirationDateTime",
    "EffectiveDateTime",
    "InformationIssueDateTime",
    "PresentationCreationDate",
    "SOPAuthorizationDateTime",
    "DigitalSignatureDateTime",
    "AttributeModificationDateTime",
    "CreationDate",
    "StructureSetDate",
    "TreatmentControlPointDate",
    "FirstTreatmentDate",
    "MostRecentTreatmentDate",
    "SafePositionExitDate",
    "SafePositionReturnDate",
    "TreatmentDate",
    "RTPlanDate",
    "SourceStrengthReferenceDate",
    "TreatmentToleranceViolationDateTime",
    "RecordedRTControlPointDateTime",
    "InterlockDateTime",
    "OverrideDateTime",
    "BeamHoldTransitionDateTime",
    "ReviewDate",
    "IntendedPhaseStartDate",
    "IntendedPhaseEndDate",
    "DateOfInstallation",
    "DateOfManufacture"
]